format = "$directory$nix_shell$git_branch$git_status\n$character\n"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](purple)"
vimcmd_symbol = "[❮](green)"

[directory]
read_only = " "
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "bright-black"

[git_status]
conflicted = "​"
deleted = "​"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
modified = "​"
renamed = "​"
staged = "​"
stashed = "≡"
style = "cyan"
untracked = "​"

[nix_shell]
format = "[ ](bold purple) "
style = "bright-purple"
